#!/bin/bash

apt-get install -y python-lzma python-gpgme pbzip2 pigz lzop

dpkg -i	\
	$INSTDIR/tools/bmaptools/bmap-tools*.deb

mkdir -p /usr/local/bin
for x in $INSTDIR/tools/scripts/*; do
	install --mode=755 $x /usr/local/bin/
done

# grab and install repo tool
wget -O /usr/local/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
chmod a+x /usr/local/bin/repo
