#!/bin/bash

apt-get autoremove -y

# remove big useless files
rm -rf /usr/lib/x86_64-linux-gnu/dri/*.so
rm -rf /usr/lib/perl/5.*/auto/Encode/JP/JP.so
rm -rf /usr/lib/perl/5.*/auto/Encode/KR/KR.so
rm -rf /usr/lib/perl/5.*/auto/Encode/CN/CN.so
rm -rf /usr/lib/perl/5.*/auto/Encode/TW/TW.so

# keep doc ?
#rm -rf /usr/share/doc
#rm -rf /usr/share/man
#rm -rf /usr/share/locale



