# .bashrc

# User specific aliases and functions
alias lsd='ls -lh'
alias lsz='ls -lZ'
alias gitlog='git log --oneline --graph --decorate'

# Handle bash history
export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
export HISTFILE=~/.bash_history
export HISTTIMEFORMAT="%d/%m/%y %T "

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

__git_ps1 ()
{
    local b="$(git symbolic-ref HEAD 2>/dev/null)";
    if [ -n "$b" ]; then
        printf "(%s)" "${b##refs/heads/}";
    fi
}

hostnam=$(hostname -s)
usernam=$(whoami)
temp="$(tty)"
#   Chop off the first five chars of tty (ie /dev/):
cur_tty="${temp:5}"
unset temp

function prompt_command {
local EXIT=$?

#   Find the width of the prompt:
TERMWIDTH=${COLUMNS}
[ $(( $TERMWIDTH % 2)) -ne 0 ] && let TERMWIDTH=$TERMWIDTH-1

#   Add all the accessories below ...
local temp="--(${usernam}@${hostnam}})-(${PWD})--"
local datesize=18

let fillsize=${TERMWIDTH}-${#temp}-$datesize
let sidesize=$fillsize/2
let rightbegin=$sidesize+$datesize
if [ "$fillsize" -gt "0" ]
then
        fill="-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
        leftfill="${fill:0:${sidesize}}"
        rightfill="${fill:${rightbegin}:${sidesize}}"
        newPWD="${PWD}"
fi

if [ "$fillsize" -lt "0" ]
then
        fill=""
        let cut=3-${fillsize}
        newPWD="...${PWD:${cut}}"
fi

local WHITE="\[\033[1;37m\]"
local NO_COLOUR="\[\033[0m\]"

local LIGHT_BLUE="\[\033[1;34m\]"
local GREEN="\[\033[1;32m\]"
local MAGENTA="\[\033[1;35m\]"
local YELLOW="\[\033[1;33m\]"
local RED="\[\033[1;31m\]"

if [ "$usernam" = "root" ]
then
    PROMPT_COLOR=$GREEN
    PROMPT_CAR="#"
else
    PROMPT_COLOR=$YELLOW
    PROMPT_CAR="$"
fi

PS1="$PROMPT_COLOR.-\
$GREEN($MAGENTA\w$GREEN)$PROMPT_COLOR--\
${PROMPT_COLOR}--\${leftfill}\
$MAGENTA\$(date \"+%a,%d %b %y\")$GREEN,$MAGENTA\$(date +%R)\
${PROMPT_COLOR}${rightfill}-\
${GREEN}($MAGENTA\u$GREEN@$MAGENTA\h$GREEN)$PROMPT_COLOR\
\n\
$PROMPT_COLOR\\\`-$GREEN(\
${MAGENTA}${EXIT}${GREEN})${PROMPT_COLOR}-$(__git_ps1)-${PROMPT_CAR}\
$NO_COLOUR "

PS2="$GREEN-$PROMPT_COLOR--$NO_COLOUR "
}

export PROMPT_COMMAND=prompt_command
