#!/bin/bash

apt-get install -y python-lzma python-gpgme pbzip2 pigz lzop

dpkg -i	\
	$INSTDIR/bmap-tools/bmap-tools*.deb

mkdir -p /usr/local/bin
for x in $INSTDIR/tools/scripts/*; do
	install --mode=755 $x /usr/local/bin/
done

